name: Release
on:
  push:
    branches:
      - "test"
  release:
    types:
      - published

permissions:
  id-token: write

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: "install"
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
        shell: bash
        
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} #app registration Application ID or user-assigned managed identity Client ID
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: "Get Azure principal token for Radix"
        run: |
          token=$(az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630 --query=accessToken -otsv)
          echo "::add-mask::$token"
          echo "APP_SERVICE_ACCOUNT_TOKEN=$token" >> $GITHUB_ENV

      - name: Deploy on Radix
        uses: equinor/radix-github-actions@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            create job
            promote
            --deploymentName: "test-from-action",
            --fromEnvironment: "test",
            --toEnvironment: "feature",
            --triggeredBy: "chbh@equinor.com"
