name: Test Flow

on:
  push:

jobs:
  test:
    name: LogInfo
    runs-on: ubuntu-latest
    if: github.ref_name != 'test-flow'
    steps:
      - name: Woohoo
        if: github.ref_name != 'test-flow'
        run: |
          echo woooohooooo
