name: Update lockfile

on:
  workflow_call:  # Called in the client-pr workflow

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update lockfile
        uses: ./.github/actions/client-build       

      - name: Check if yarn.lock has changed
        id: check-yarn-lock
        run: |
          git add yarn.lock
          if [ -n "$(git diff --cached --exit-code)" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi
        shell: bash        

      - name: Commit and push changes
        if: steps.update-yarn-lock.outputs.changed == 'true'
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -n -m "chore(snyk): update lockfile"
            git push
            