name: Update lockfile

on:
  workflow_dispatch:
  pull_request:
    branches:
      - snyk-upgrade-*

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update lockfile
        run: pnpm i --lockfile-only

      - name: Commit and push changes
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'  
            git add package-lock.json
            git commit -m "chore(snyk): update lockfile"
            git push